DECIMAL_ROUNDING = 6

BOUNDS = [-10, 10]
DIMENSIONS = 10

POPULATION_SIZE = int(1e2)

GENERATE_INITIAL_POPULATION_RANDOM = True
CREATE_INITIAL_POPULATION_SIZE = 100
CREATE_INITIAL_POPULATION_RECOMBINATIONS_PER_ITERATION = int(1e1)
CREATE_INITIAL_ITERATIONS = int(1e2)

TARGET_OPTIMIZATION_POPULATION_SIZE = int(1e2)
TARGET_OPTIMIZATION_POPULATION_RECOMBINATIONS_PER_ITERATION = int(1e3)
TARGET_OPTIMIZATION_ITERATIONS = int(1e3)

CROSSOVER_RANGE = [int(DIMENSIONS * 0.2), int(DIMENSIONS * 0.8) + 1]

ITERATIVE_OPTIMIZATION_CONTINUE_TRAINING_AFTER_CYCLES = 1
ITERATIVE_OPTIMIZATION_INITIAL_POPULATION_SIZE = int(1e3)
ITERATIVE_OPTIMIZATION_POPULATION_SIZE = int(1e1) * 1
ITERATIVE_OPTIMIZATION_RECOMBINATIONS_PER_ITERATION = int(1e3) * 1
ITERATIVE_OPTIMIZATION_ITERATIONS_PER_CYCLE = int(1e1) * 10
ITERATIVE_OPTIMIZATION_CYCLES = int(1e1) * 4

CONTINUE_TRAINING_BATCH_SIZE = 10
CONTINUE_TRAINING_EPOCHS = 1000
CONTINUE_TRAINING_VALIDATION_SPLIT = 0.2

OPTIMIZATION_TRAIN_NEW_MODEL = False

TRAINING_VALIDATION_SPLIT = 0.2
TRAINING_DROPOUT_RATE = 0.8
TRAINING_L2_REGULARIZATION = 0.0025
TRAINING_L1_REGULARIZATION = 0.05
TRAINING_HIDDEN_LAYER_SIZE = 256
TRAINING_BATCH_SIZE = 10
TRAINING_EPOCHS = 5000
TRAINING_OPTIMIZER = "adam"
TRAINING_LOSS = "mean_squared_error"
TRAINING_METRICS = [
    "mean_squared_error", # Same as loss
    "mean_absolute_error",
    "mean_absolute_percentage_error",
]

FITNESS_FUNCTION = "rosenbrock"
MODEL_SAVE_FORMAT = "h5"
MODEL_PATH = f"models\\{FITNESS_FUNCTION}.{MODEL_SAVE_FORMAT}"
POPULATION_PATH = f"storage\\{FITNESS_FUNCTION}.txt"

SCALE = 1. / (BOUNDS[1] - BOUNDS[0])
OFFSET = BOUNDS[0]

MONTE_CARLO_TEST_POPULATION_SIZE = int(1e4)

PLOT_LABEL_FONT_SIZE = 22
PLOT_TICKS_FONT_SIZE = 20