DECIMAL_ROUNDING = 15

# TODO - gmausa@riteh.hr github
# TODO - https://blog.chih.me/read-cpu-power-with-RAPL.html - LINUX
# skica modela, grafički podaci, trendovi, error modela, arhitektura optimizacije, hiperoptimizacija?
# activation function range, regression?

BOUNDS = [-5, 5]
DIMENSIONS = 200

POPULATION_SIZE = int(1e3)
INITIAL_POPULATION_SIZE = 400
POPULATION_SIZE_PER_ITERATION = 100
ITERATIONS = 0

OPTIMIZATION_INITIAL_POPULATION_SIZE = int(1e1) * 5
OPTIMIZATION_POPULATION_SIZE_PER_ITERATION = int(1e3)
OPTIMIZATION_ITERATIONS = int(1e3)

ITERATIVE_OPTIMIZATION_INITIAL_POPULATION_SIZE = int(1e1) 
ITERATIVE_OPTIMIZATION_POPULATION_SIZE_PER_ITERATION = int(1e4)
ITERATIVE_OPTIMIZATION_ITERATIONS_PER_CYCLE = int(1e2)
ITERATIVE_OPTIMIZATION_CYCLES = int(1e1) * 10

FITNESS_FUNCTION = "rosenbrock"
MODEL_SAVE_FORMAT = "h5"
MODEL_PATH = f"models\\{FITNESS_FUNCTION}.{MODEL_SAVE_FORMAT}"
POPULATION_PATH = f"storage\\{FITNESS_FUNCTION}.txt"

SCALE = 1. / (BOUNDS[1] - BOUNDS[0])
OFFSET = BOUNDS[0]

MONTE_CARLO_TEST_POPULATION_SIZE = int(1e4)